name: papi-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.10.0
  - numpy>=1.20.0
  - pip>=21.0.0
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - tqdm>=4.62.0
  - seaborn>=0.11.2
  - pip:
    - transformers>=4.18.0
    - datasets>=2.0.0
    - tensorboard>=2.8.0
    - pytest>=7.0.0